### ISSUE TITLE
Fatal error: Cannot use object of type WP_Term as array

### ISSUE THREAD

**Issue by aguilar1181** [jaycbrf4/WP-Bootstrap4-MegaMenu-Navwalker#1]
$location = 'primary_menu';
$css_class = 'mega-menu-parent';
$locations = get_nav_menu_locations();
if (isset($locations[$location])){
	$menu = get_term($locations[$location], 'nav_menu');
	
	if($items = wp_get_nav_menu_items($menu->name)){
		foreach ( $items as $item ) {
			if ( in_array( $css_class, $item->classes ) ) {
				register_sidebar( array(
					'id'   => 'mega-menu-item-' . $item->ID,
					'description' => 'Mega Menu items',
					'name' => $item->title . ' - Mega Menu',
					'before_widget' => '<li id="%1$s" class="mega-menu-item">',
					'after_widget' => '</li>', 
				));
			}
		}
	}
}

The code above to generate the widget for each menu item is returning an error.

**Comment by dvkdesigns** [comment]
I am having the same issue.

**Comment by kvn1234** [comment]
You probably haven't wrapped it in a function. My theme's structure is a bit different, but you probably need to do something like:

```
function wp_items_megamenu_init() {
    $location = 'primary';
    $css_class = 'mega-menu-parent';
    $locations = get_nav_menu_locations();
    if ( isset( $locations[ $location ] ) ) {
        $menu = get_term( $locations[ $location ], 'nav_menu' );
        if ( $items = wp_get_nav_menu_items( $menu->name ) ) {
            foreach ( $items as $item ) {
                if ( in_array( $css_class, $item->classes ) ) {
                    register_sidebar( array(
                        'id'   => 'mega-menu-item-' . $item->ID,
                        'description' => 'Mega Menu items',
                        'name' => $item->title . ' - Mega Menu',
                        'before_widget' => '<li id="%1$s" class="mega-menu-item">',
                        'after_widget' => '</li>',

                    ));
                }
            }
        }
    }
}

add_action( 'widgets_init', 'wp_items_megamenu_init' );
```
